name: AutoDoc Update

on: 
  pull_request_review:
    types: [submitted]

jobs:
  update:                                                                     
    runs-on: ubuntu-latest
    if: github.event.review.state == 'approved'
    environment: autodoc-approval
    permissions:                                                                               
        pull-requests: write                                                                     
        contents: write  
